{
 "title": "Lab IoT UNMSM – Grupo g1",
 "tags": [
  "unmsm",
  "iot",
  "mqtt",
  "g1"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latest temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"temperatura\") FROM \"sensor_dht22\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "SELECT mean(\"temperatura\") FROM \"sensor_dht22\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "SELECT mean(\"humedad\") FROM \"sensor_dht22\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(none)"
    }
   ]
  }
 ]
}