/* ===========================================================================
 * Lab 08 — ECIES encrypted publisher (ESP32-S3)
 *
 * Reads DHT22 (temp/hum), BME280 (pressure), MQ-2 (gas), encrypts the JSON
 * with ECIES (ephemeral ECDH P-256 + SHA-256 KDF + AES-128-CTR) and publishes
 * the Base64 ciphertext to:
 *   unmsm/iot2025/lab-a/g1/sensores/json_enc   (Base64, QoS 0)
 *
 * The broker only sees opaque bytes; only Node-RED (holding the ECC private
 * key) can decrypt. A fresh ephemeral keypair per message => Perfect Forward
 * Secrecy.
 *
 * Wire format (before Base64):
 *   [ eph_pub_x(32) | eph_pub_y(32) | nonce(16) | ciphertext(N) ]
 *
 * Client ID: esp32-g1-ecc
 *
 * Libraries (Library Manager): WiFi, PubSubClient (knolleary),
 *   DHT sensor library (Adafruit), Adafruit BME280, Adafruit Unified Sensor,
 *   ArduinoJson, micro-ecc (Ken MacKay — search "micro-ecc"). mbedtls ships
 *   with the ESP32 Arduino core.
 *
 * Run scripts/ecc-keygen.sh FIRST: it generates ecc_public_key.h (included
 * below) plus the matching private key for Node-RED.
 *
 * NOTE on QoS: PubSubClient::publish() is always QoS 0. See project README.
 * =========================================================================== */

#include <WiFi.h>
#include <PubSubClient.h>
#include <Wire.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_BME280.h>
#include <DHT.h>
#include <ArduinoJson.h>
#include <uECC.h>
#include <esp_random.h>
#include <mbedtls/aes.h>
#include <mbedtls/sha256.h>
#include "arduino_secrets.h"
#include "ecc_public_key.h"   // AUTO-GENERATED by scripts/ecc-keygen.sh

// --- Identity & namespace (EXACT lab namespace) -----------------------------
static const char* DEVICE_ID    = "esp32-g1-ecc";
static const char* TOPIC_ENC    = "unmsm/iot2025/lab-a/g1/sensores/json_enc";
static const char* TOPIC_STATUS = "unmsm/iot2025/lab-a/g1/status";

// --- Hardware ---------------------------------------------------------------
#define DHT_PIN      4
#define DHT_TYPE     DHT22
#define BME280_ADDR  0x76
#define MQ2_AO_PIN   36
#define MQ2_DO_PIN   35

// --- Tuning -----------------------------------------------------------------
static const unsigned long PUBLISH_INTERVAL_MS = 10000;  // every 10 s
static const int           GAS_THRESHOLD       = 2000;
static const uint16_t      MQTT_PORT           = 1883;

DHT dht(DHT_PIN, DHT_TYPE);
Adafruit_BME280 bme;
WiFiClient   wifiClient;
PubSubClient mqtt(wifiClient);

bool          bmeOk       = false;
unsigned long lastPublish = 0;

// ===========================================================================
// ECIES primitives
// ===========================================================================
static int rng_function(uint8_t* dest, unsigned size) {
  esp_fill_random(dest, size);
  return 1;
}

// aes_key(16) = SHA256( shared_x(32) || eph_pub_x(32) )[:16]
static void kdf(const uint8_t* shared_x, const uint8_t* eph_pub_x, uint8_t* aes_key) {
  uint8_t in[64];
  memcpy(in,      shared_x,  32);
  memcpy(in + 32, eph_pub_x, 32);
  uint8_t hash[32];
  mbedtls_sha256(in, 64, hash, 0);   // 0 => SHA-256
  memcpy(aes_key, hash, 16);
}

// AES-128-CTR (same call encrypts & decrypts; CTR uses the forward key only).
static void aes_ctr_crypt(const uint8_t* key, const uint8_t* nonce16,
                          const uint8_t* in, uint8_t* out, size_t len) {
  mbedtls_aes_context aes;
  mbedtls_aes_init(&aes);
  mbedtls_aes_setkey_enc(&aes, key, 128);
  uint8_t nonce_counter[16];
  memcpy(nonce_counter, nonce16, 16);
  uint8_t stream_block[16] = {0};
  size_t  nc_off = 0;
  mbedtls_aes_crypt_ctr(&aes, len, &nc_off, nonce_counter, stream_block, in, out);
  mbedtls_aes_free(&aes);
}

// Output: [eph_pub_x(32)|eph_pub_y(32)|nonce(16)|ct(N)]. Returns total len or 0.
static size_t ecies_encrypt(const uint8_t* pt, size_t pt_len,
                            uint8_t* out, size_t out_max) {
  const struct uECC_Curve_t* curve = uECC_secp256r1();
  uECC_set_rng(rng_function);

  uint8_t eph_priv[32], eph_pub[64];            // (r, R = r*G)
  if (!uECC_make_key(eph_pub, eph_priv, curve)) return 0;

  uint8_t pub_recv[64];                         // Q = subscriber public key
  memcpy(pub_recv,      ecc_pub_x, 32);
  memcpy(pub_recv + 32, ecc_pub_y, 32);

  uint8_t shared[32];                           // S.x = (r*Q).x
  if (!uECC_shared_secret(pub_recv, eph_priv, shared, curve)) return 0;

  uint8_t aes_key[16];
  kdf(shared, eph_pub, aes_key);                // eph_pub first 32 bytes = X

  uint8_t nonce[16];
  esp_fill_random(nonce, 16);

  const size_t header = 64 + 16;
  if (header + pt_len > out_max) return 0;
  memcpy(out,      eph_pub, 64);
  memcpy(out + 64, nonce,   16);
  aes_ctr_crypt(aes_key, nonce, pt, out + header, pt_len);
  return header + pt_len;
}

static size_t base64_encode(const uint8_t* data, size_t len, char* out) {
  static const char T[] =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  size_t o = 0, i = 0;
  for (; i + 3 <= len; i += 3) {
    uint32_t n = ((uint32_t)data[i] << 16) | ((uint32_t)data[i+1] << 8) | data[i+2];
    out[o++] = T[(n >> 18) & 63]; out[o++] = T[(n >> 12) & 63];
    out[o++] = T[(n >> 6) & 63];  out[o++] = T[n & 63];
  }
  size_t rem = len - i;
  if (rem == 1) {
    uint32_t n = (uint32_t)data[i] << 16;
    out[o++] = T[(n >> 18) & 63]; out[o++] = T[(n >> 12) & 63];
    out[o++] = '='; out[o++] = '=';
  } else if (rem == 2) {
    uint32_t n = ((uint32_t)data[i] << 16) | ((uint32_t)data[i+1] << 8);
    out[o++] = T[(n >> 18) & 63]; out[o++] = T[(n >> 12) & 63];
    out[o++] = T[(n >> 6) & 63];  out[o++] = '=';
  }
  out[o] = '\0';
  return o;
}

// ===========================================================================
void connectWiFi() {
  Serial.printf("[WiFi] Connecting to %s", SECRET_WIFI_SSID);
  WiFi.mode(WIFI_STA);
  WiFi.begin(SECRET_WIFI_SSID, SECRET_WIFI_PASS);
  while (WiFi.status() != WL_CONNECTED) { delay(400); Serial.print('.'); }
  Serial.printf("\n[WiFi] Connected. IP: %s\n", WiFi.localIP().toString().c_str());
}

void connectMQTT() {
  while (!mqtt.connected()) {
    Serial.print("[MQTT] Connecting to broker...");
    bool ok = mqtt.connect(DEVICE_ID, nullptr, nullptr,
                           TOPIC_STATUS, 0, true, "offline");   // LWT
    if (ok) {
      Serial.println(" connected.");
      mqtt.publish(TOPIC_STATUS, "online", true);
    } else {
      Serial.printf(" failed (rc=%d). Retry in 2s.\n", mqtt.state());
      delay(2000);
    }
  }
}

void publishEncrypted() {
  float temperatura = dht.readTemperature();
  float humedad     = dht.readHumidity();
  float presion     = bmeOk ? bme.readPressure() / 100.0F : 0.0F;
  int   gas         = analogRead(MQ2_AO_PIN);
  bool  alerta      = (gas >= GAS_THRESHOLD) || (digitalRead(MQ2_DO_PIN) == LOW);

  if (isnan(temperatura) || isnan(humedad)) {
    Serial.println("[DHT22] Read failed — skipping cycle.");
    return;
  }

  StaticJsonDocument<256> doc;
  doc["dispositivo"] = DEVICE_ID;
  doc["temperatura"] = round(temperatura * 100) / 100.0;
  doc["humedad"]     = round(humedad * 100) / 100.0;
  doc["presion_hpa"] = round(presion * 10) / 10.0;
  doc["gas_raw"]     = gas;
  doc["alerta_gas"]  = alerta;
  doc["rssi"]        = WiFi.RSSI();

  char json[256];
  size_t jsonLen = serializeJson(doc, json);

  uint8_t enc[512];
  size_t encLen = ecies_encrypt((uint8_t*)json, jsonLen, enc, sizeof(enc));
  if (encLen == 0) { Serial.println("[ECC] encrypt error"); return; }

  char b64[700];
  base64_encode(enc, encLen, b64);

  bool ok = mqtt.publish(TOPIC_ENC, b64);
  Serial.printf("[ECC] %s  plain=%.2fC/%.1f%%  ct=%uB\n",
                ok ? "published" : "publish FAILED",
                temperatura, humedad, (unsigned)encLen);
}

void setup() {
  Serial.begin(115200);
  delay(200);
  dht.begin();
  pinMode(MQ2_DO_PIN, INPUT);
  analogReadResolution(12);
  Wire.begin(21, 22);
  bmeOk = bme.begin(BME280_ADDR);
  if (!bmeOk) Serial.println("[BME280] not found at 0x76 — pressure will be 0.");
  connectWiFi();
  mqtt.setServer(SECRET_MQTT_BROKER, MQTT_PORT);
  mqtt.setBufferSize(1024);   // ciphertext + Base64 exceeds the 256-byte default
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) connectWiFi();
  if (!mqtt.connected())             connectMQTT();
  mqtt.loop();
  unsigned long now = millis();
  if (now - lastPublish >= PUBLISH_INTERVAL_MS) {
    lastPublish = now;
    publishEncrypted();
  }
}
